/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f1f4f6",
        "secondary-fixed": "#d6e4f5",
        "tertiary-dim": "#285c53",
        "primary-dim": "#285582",
        "tertiary-fixed": "#c8fff2",
        "surface": "#f8f9fa",
        "surface-container-high": "#e3e9ec",
        "on-secondary": "#f6f9ff",
        "inverse-surface": "#0c0f10",
        "secondary": "#53606f",
        "on-tertiary-container": "#31645b",
        "primary-fixed-dim": "#b9d7ff",
        "inverse-primary": "#92bcf0",
        "tertiary-container": "#c8fff2",
        "on-secondary-container": "#455361",
        "on-error": "#fff7f6",
        "primary-container": "#d2e4ff",
        "outline-variant": "#abb3b7",
        "secondary-container": "#d6e4f5",
        "tertiary-fixed-dim": "#baf0e4",
        "secondary-fixed-dim": "#c7d6e7",
        "error-container": "#fe8983",
        "background": "#f8f9fa",
        "inverse-on-surface": "#9b9d9e",
        "surface-tint": "#35618f",
        "error-dim": "#4e0309",
        "surface-variant": "#dbe4e7",
        "tertiary": "#35685e",
        "on-primary-container": "#275482",
        "secondary-dim": "#475563",
        "surface-bright": "#f8f9fa",
        "on-primary": "#f5f7ff",
        "on-tertiary": "#e3fff7",
        "on-tertiary-fixed-variant": "#3c6f65",
        "outline": "#737c7f",
        "primary": "#35618f",
        "error": "#9f403d",
        "on-tertiary-fixed": "#1d5249",
        "on-primary-fixed-variant": "#325e8c",
        "on-surface-variant": "#586064",
        "primary-fixed": "#d2e4ff",
        "surface-container-highest": "#dbe4e7",
        "on-surface": "#2b3437",
        "on-error-container": "#752121",
        "on-secondary-fixed": "#33414e",
        "on-secondary-fixed-variant": "#4f5d6b",
        "surface-container-lowest": "#ffffff",
        "on-background": "#2b3437",
        "on-primary-fixed": "#0d416e",
        "surface-container": "#eaeff1",
        "surface-dim": "#d1dce0"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
